name: Add Comment flow

on:
  pull_request:
    branches:
      - master
    paths:
      - addComment/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: addcomment/checkout@master
      - uses: caneesh/addcomment/@master
        with:
          pull_number: '3'
          repo-token: ${{ secrets.GITHUB_TOKEN }}